directories:
  output: release
  buildResources: build
appId: com.xun.notes
productName: Xun
files:
  - filter:
      - dist/**/*
mac:
  category: public.app-category.productivity
  icon: resources/icon.icns
  target: dmg
electronVersion: 39.2.5
